name: Build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest

    steps:      
      - uses: actions/checkout@v2

      #- name: Setup MSBuild
      #  uses: microsoft/setup-msbuild@v1

      - name: Setup devenv
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      #- name: Setup VSTest
      #  uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      #- name: Restore Packages
      #  run: nuget restore OneMore.sln

      #- name: Build Solution
      #  run: |
      #    msbuild.exe Sandbox.sln /p:platform="Any CPU" /p:configuration="Release"

      #- name: Run Tests
      #  run: vstest.console.exe .\tests\Sandbox.Tests\bin\Release\Sandbox.Tests.dll

      - name: Build solution
        run: .\build.ps1
